### ISSUE TITLE
Error: NoViewManager defined for Class RNSVGrect

### ISSUE THREAD

**Issue by fawwaz** [wonsikin/react-native-barcode-builder#1]
Helo @wonsikin , i got the `NoViewManager defined for Class RNSVGrect` exception, do you know how to handle that ? 

Edit: I've read this one : https://github.com/react-native-community/react-native-svg/issues/148, and I can guarantee that I've linked the react-native-svg dependency correctly. However, it still does'nt work. Do you have any advice ?

**Comment by wonsikin** [comment]
@fawwaz Which platform do you app run? Android or iOS?

**Comment by fawwaz** [comment]
Android, well , finally I've found the solution. 
In my case, I just need to re-run `react-native run-android` again. It seems that `react-native-svg` add some java dependency on `MainApplication.java`. I forget to "update" the java dependency that installed in my device so once I run `react-native run-android` gradle will "download" `com.horcrux.svg.RNSvgPackage` as said in https://github.com/react-native-community/react-native-svg/issues/135
