### ISSUE TITLE
No component found for view with name "RNSVGRect"

### ISSUE THREAD

**Issue by Jaiborge** [wonsikin/react-native-barcode-builder#10]
Error where calling Barcode

![image](https://cloud.githubusercontent.com/assets/27086796/26187620/f0bef248-3b5f-11e7-906d-4dd4ad6f785d.png)

**Comment by MSchmidt** [comment]
Sound like ``react-native link react-native-svg`` didn't do all it's work for you. Install ``react-native-svg`` manually into your iOS Xcode Project.
