### ISSUE TITLE
Text prop does not work

### ISSUE THREAD

**Issue by nolan-m** [wonsikin/react-native-barcode-builder#28]
According to the docs, setting a value to the text prop should override text that is displayed.  I do not see any text displayed.  I'm assuming the default text displayed should be the value.  

`<Barcode value="Hello World" format="CODE128" text="This is displayed" />`

**Comment by raven-chen** [comment]
same here. I just made a PR https://github.com/wonsikin/react-native-barcode-builder/pull/30
