### ISSUE TITLE
EAN13 encoder doesn't work ('undefined is not an object when evaluating binary.length')

### ISSUE THREAD

**Issue by kiddi** [wonsikin/react-native-barcode-builder#4]
Trying to use the library to create EAN13 barcodes, but run into:

`undefined is not an object when evaluating binary.length`

This doesn't happen when I use a different barcode type (Code128 for example), but I think it's the for loop in `drawSvgBarCode()` that doesn't work with EAN13

**Comment by wonsikin** [comment]
@kiddi You can add `flat` property like the following:
```
  <Barcode value="1234567890128" format="EAN13" flat />
```
This will generate a barcode like the following picture:
![image](https://cloud.githubusercontent.com/assets/6659426/22860979/2e132fe0-f148-11e6-95d5-743951d56912.png)

But if you want to generate a barcode like bellow:
![image](https://cloud.githubusercontent.com/assets/6659426/22860982/3d4491d4-f148-11e6-8e97-bfec58211ebc.png)

I will say sorry.

If you can help me to improve this repository, I will appreciate it.

**Comment by kiddi** [comment]
Thanks for the tip, I'll see if I can make it better :)

**Comment by KonstantinZhukovskij** [comment]
any news here?
