### ISSUE TITLE
replace componentWillUpdate to something other

### ISSUE THREAD

**Issue by avasuro** [wonsikin/react-native-barcode-builder#47]
This library uses property **componentWillUpdate** in source code. In React 17 this property will be removed, and React 16 throws a warning about this property should not be used. Please replace this property with some alternative to suppress a warning (e.g. getDerivedStateFromProps).

Here is some more information: https://ru.reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by CyrusZei** [comment]
it should be replaced with componentDidMount

**Comment by yaghami** [comment]
Into archive /node_modules/react-native-barcode-builder/index.js line 51, just replace method componentWillUpdate for componentDidUpdate

**Comment by wonsikin** [comment]
Please refer to [ComponentDidUpdate instead of ComponentWillUpdate](https://github.com/wonsikin/react-native-barcode-builder/commit/4a7fcc8056a0d64835607b4d3fb1ff0961cd84de#diff-168726dbe96b3ce427e7fedce31bb0bc)
