### ISSUE TITLE
Handling of invalid barcode

### ISSUE THREAD

**Issue by tiaanduplessis** [wonsikin/react-native-barcode-builder#5]
Thank you for the module 👍 .

Would you consider if instead of throwing an error for invalid barcode, the component provides an onError property to handle it? I'm using the module in App where the user inputs the barcode value and instead of adding custom validation  it would make sense to use the existing validation provided by jsBarcode within the module. Would be happy to do the PR.

**Comment by wonsikin** [comment]
@tiaanduplessis I'm looking forward your PR.

**Comment by tiaanduplessis** [comment]
#8
