### ISSUE TITLE
React Native ART has been moved. Please update 

### ISSUE THREAD

**Issue by DanielDanaee** [wonsikin/react-native-barcode-builder#52]
`ExceptionsManager.js:126 Warning: React Native ART has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'. See https://github.com/react-native-community/art`

**Comment by mindcube** [comment]
Running into this issue as well.  Will submit a PR with fix asap.

**Comment by wonsikin** [comment]
#51
