### ISSUE TITLE
Warning: React Native ART has been extracted from react-native core

### ISSUE THREAD

**Issue by yt-dev** [wonsikin/react-native-barcode-builder#57]
Warning: React Native ART has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'. See https://github.com/react-native-community/art

**Comment by wonsikin** [comment]
@yt-dev Yup! You can upgrade it to the version 2.0.0 
https://www.npmjs.com/package/react-native-barcode-builder
