### ISSUE TITLE
SurfaceView should have explicit width and height set

### ISSUE THREAD

**Issue by nisalperi** [wonsikin/react-native-barcode-builder#7]
I get this error on Android. Any ideas?

**Versions**

`"react-native-svg": "^5.1.7"`
`"react-native-barcode-builder": "^0.2.1"`

![screenshot_1492757274](https://cloud.githubusercontent.com/assets/5406405/25265863/4ec2cb7a-26b2-11e7-8498-d1771e6f1bfb.png)

**Comment by wonsikin** [comment]
@nisalperi Please use the latest version and try again. I had replace the react-native-svg with ART #12
