### ISSUE TITLE
PDF417 support

### ISSUE THREAD

**Issue by dmacan23** [wonsikin/react-native-barcode-builder#9]
Hi, can you add please PDF417 barcode support? Many POS devices use it and I think that it would be a great addition to the library

**Comment by wonsikin** [comment]
[Support PDF417](https://github.com/lindell/JsBarcode/issues/159)

**Comment by wonsikin** [comment]
@dmacan23 I find a package supports PDF417

[react-native-barcode-pdf417](https://github.com/GingerBear/react-native-barcode-pdf417)
